### PR TITLE
Add default value to get command

### PR DESCRIPTION
**Pull request by dotKuro**
I set the default for the get command to "state:open" as stated in #18

### CODE REVIEW

**Comment by dotKuro** [comment]
Just ignore the last two commits. The first one should be pushed to another branch and the second one just reverts the first one. :see_no_evil:

**Comment by dotKuro** [comment]
No `tl get state:done` works perfectly using this method. The parser looks for at least one string argument other whise it will fail. The <|> provides an alternaitve in case the parser fails. Which means it will either use any arguemnt provided (i.e `tl get state:done`) or when no arguemnt is provided (`tl get`) it will use state:open instead.

**Comment by ad-si** [comment]
Ah ok, sorry, didn't properly read the code.

But this means that `tl get` would list all open tasks like `tl open`.
I think I'd prefer that it shows the help text if the filter expressions is misssing:

```
$ tl get
Missing: FILTER_EXP

Usage: tasklite get FILTER_EXP
  Get all tasks filtered by the specified expressions by priority
```

**Comment by dotKuro** [comment]
This is exactly the behaviour upstream has currently.

I propably missunderstood the todo.

``` (40gs) Use state:open per default for the tl get command```

What was this suppose to mean? If you not specify `state:` after get it should always implicitly use `state:open`?

**Comment by ad-si** [comment]
If there is a filter without a `state` expression
then add expression `state:open`
else (there is no filter) show help message

**Comment by ad-si** [comment]
Added in 826aa99.
Thanks a lot for the PR!

**Pull request closed without merging**
